src/faebryk/tools/libadd.py

Shortcut to quickly create new library files
Call with python -m faebryk.tools.libadd
Useable for both faebryk and local modules.
```bash
> python -m faebryk.tools.libadd --no-local has_test trait --defined
File faebryk/faebryk/src/faebryk/library/has_test.py created
File faebryk/src/faebryk/library/has_test_defined.py created
```
```bash
> python -m faebryk.tools.libadd --no-local TI_555 module
File faebryk/src/faebryk/library/TI_555.py created
```

Tools: libadd

---

src/faebryk/exporters/visualize/interactive_graph.py
src/faebryk/exporters/visualize/util.py

Add interactive graph viewer

---

examples/signal_processing.py
src/faebryk/core/parameter.py
src/faebryk/library/ElectricLogic.py
src/faebryk/library/Filter.py
src/faebryk/library/FilterElectricalLC.py
src/faebryk/library/Logic.py
src/faebryk/library/Signal.py
src/faebryk/library/SignalElectrical.py
src/faebryk/library/_F.py
src/faebryk/library/has_construction_dependency.py
src/faebryk/library/has_descriptive_properties_defined.py
src/faebryk/library/has_multi_picker.py
src/faebryk/library/has_parameter_construction_dependency.py

Reopened from https://github.com/faebryk/faebryk/pull/197

Lib: Filters & Signals & Delayed construction

---

src/faebryk/exporters/pcb/kicad/transformer.py
src/faebryk/libs/kicad/fileformats.py

- [Fix: vias only have 1 size value](https://github.com/atopile/faebryk/commit/54a747e4908f5f1a13555d4c0eae2968451d5aac)
- [Add: DNP footprint attr](https://github.com/atopile/faebryk/commit/85729e92abd4cf8d9d900442fd3fb1f37c2859e2)
- [Add: Island bool for filled polygons](https://github.com/atopile/faebryk/commit/2aa0fb9dc93fe28f3ac097e36fe65a5dcf2b1e8d)

Bug: KiCad: Fileformat: missing island, dnp, via

---

src/faebryk/libs/picker/jlcpcb/jlcpcb.py
src/faebryk/libs/picker/jlcpcb/picker_lib.py
src/faebryk/libs/picker/jlcpcb/pickers.py
src/faebryk/libs/pycodegen.py
src/faebryk/tools/libadd.py

Adding --mfr or --lcsc to libadd will now result in automatically adding
datasheets, designator, name, descriptive\_properties, interfaces & pin
heuristics to the module.
`❯ faebryk libadd STM32G030K6T6 module --mfr`
```python
import logging
import faebryk.library._F as F  # noqa: F401
from faebryk.core.module import Module
from faebryk.libs.library import L  # noqa: F401
from faebryk.libs.picker.picker import DescriptiveProperties
from faebryk.libs.units import P  # noqa: F401
logger = logging.getLogger(__name__)
class STMicroelectronics_STM32G030K6T6(Module):
"""
TODO: Docstring describing your module
32KB 2V~3.6V ARM-M0 8KB 64MHz FLASH 30 LQFP-32(7x7)
Microcontrollers (MCU/MPU/SOC) ROHS
"""
NRST: F.Electrical
PA0: F.Electrical
PA1: F.Electrical
PA10: F.Electrical
PA11PA9: F.Electrical …
```

Tools: Add lcsc & mfr flag to libadd for auto-module

---

.github/workflows/pre-commit.yml
src/faebryk/core/node.py

Explicitly run pre-commit in CI on every task.
This means someone not having `pre-commit` goes from being bad for us to just bad for them. Ideal 👌

CI: explicity execute pre-commit in CI on PRs

---

src/faebryk/library/LED.py
src/faebryk/library/LEDIndicator.py
src/faebryk/library/PoweredLED.py
src/faebryk/library/_F.py

Library: PoweredLED: Option to move resistor on A or K side

---

examples/iterative_design_nand.py
examples/signal_processing.py
src/faebryk/libs/app/erc.py
src/faebryk/libs/examples/buildutil.py

ERC: Check ElectricPower has voltage

---

src/faebryk/libs/sexp/dataclass_sexp.py

Add stack information to the SEXP decoder so we can traceback errors more easily

SEXP: Add stack and debugging information to decoder

---

src/faebryk/libs/sexp/dataclass_sexp.py

Add debugging info for dumping unprocessed entities

SEXP: Debug warning of unprocessed SEXPs

---

src/faebryk/core/graphinterface.py
src/faebryk/libs/kicad/fileformats.py
src/faebryk/libs/kicad/fileformats_common.py
src/faebryk/libs/kicad/fileformats_sch.py
src/faebryk/libs/sexp/dataclass_sexp.py
src/faebryk/libs/util.py
test/libs/kicad/test_fileformats.py

Add KiCAD schematic fileformat support

Core: KiCAD Sch Fileformat

---

.github/workflows/pytest.yml
poetry.lock
pyproject.toml

```
====================================================================================================== test session starts ======================================================================================================
platform darwin -- Python 3.12.3, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/mattwildoer/Projects/faebryk-wt1
configfile: pyproject.toml
plugins: xdist-3.6.1
8 workers [547 items]   
......................................................................................................................................................................................................................... [ 39%]
.................................................................................................................................................................. …
```

Test: Accelerate pytests with some parallelisation

---

src/faebryk/libs/kicad/fileformats.py

Nested groups in KiCad is possible, this is just a new group with the UUIDs of the nested groups in the members list.

Lib: kicad: fileformat: Add support for groups

---

src/faebryk/libs/kicad/fileformats_common.py

Add: kicad: fileformat_common: Missing stroke types

---

src/faebryk/libs/util.py
test/libs/test_util_func_collections.py

Provides convenient classes to manage unhashable collections.

Core: Add FuncSet and FuncDict modules to lib/util

---

src/faebryk/exporters/pcb/layout/next_to.py

```python
self.led.current_limiting_resistor.add(
F.has_pcb_layout_defined(LayoutNextTo(self.led.led.cathode))
)
```

Layout: Add NextTo

---

src/faebryk/libs/kicad/fileformats.py

Some of KiCads default library footprints are missing these values :roll_eyes: 

Libs: KiCad: Fileformat: Fix missing defaults

---

examples/minimal_led_orderable.py
src/faebryk/exporters/pcb/kicad/pcb.py

:slightly_smiling_face: 
Fixes #88 

Exporter: PCB: Fix: PCB net numbers

---

src/faebryk/exporters/pcb/kicad/pcb.py

Exporter: Kicad: PCB: Add faebryk name and LCSC number to footprint properties

---

src/faebryk/exporters/pcb/kicad/pcb.py
src/faebryk/exporters/schematic/kicad/transformer.py
src/faebryk/libs/kicad/paths.py

Adds KiCad global footprint paths for non-linux platforms, in place of hardcoded `~/.config` and `/usr/share` paths.
Fixes
```
FileNotFoundError: [Errno 2] No such file or directory:
'/Users/<user>/.config/kicad/8.0/fp-lib-table'
```
on macOS.
TODO: test on Windows

Exporter: Cross-platform KiCad footprint paths

---

src/faebryk/libs/geometry/basic.py
test/libs/geometry/test_basic.py

`Geometry.rotate` was doing translations out of order, which manifested grossly for off-origin-axes.
This fixes it

Fix geometry rotation

---

src/faebryk/libs/kicad/fileformats.py

Expected file contents:
```
(fp_lib_table
(version 7)
(lib ...)
)
```
On my machine:
```
(fp_lib_table
(lib ...)
)
```
Resulting in `DecodeError: Failed to decode fp_lib_table`
This allows for decoding in both cases.
TODO: retain the version number check, when present

Fix: Libs: KiCad: Fileformat: Permit `version` key in `fp-lib-table` file to be absent

---

src/faebryk/libs/kicad/paths.py

Fix: Exporter: Global footprint library dir path for macOS

---

src/faebryk/libs/util.py

The `keys` and `values` were properties of the `FuncDict` and `FuncSet` classes. To mimic dicts and sets they should be called.

libs: Normalize FuncDict and FuncSet util collections key and value callables

---

src/faebryk/core/cpp/__init__.py

On OSx, the architecture mightn't be reliably auto-detected because Macs try to abstract some of the hard stuff.
This PR explicitly detects and adds a build flag for the right architecture on OSx. 
Additionally, it adds logging of the stderr stream on failures for debugging

Core: Build wheels for the appropriate architecture on OSx devices

---

src/faebryk/libs/picker/jlcpcb/jlcpcb.py
src/faebryk/libs/picker/jlcpcb/picker_lib.py

When picking a part by LCSC ID or MFR attach the parsed parameters to the module.

Bugfix: Picker: Attach params on ID or MFR pick

---

src/faebryk/core/cpp/CMakeLists.txt
src/faebryk/core/cpp/__init__.py
src/faebryk/libs/util.py
test/core/cpp/test_importcpp.py

- Fix bug where pytest builds would fail because of system vs. venv python difference
- Improve editable installation detection robustness

Core: Fix pytest rebuilder and improve editable installation detection

---

src/faebryk/libs/picker/api/api.py
src/faebryk/libs/picker/api/picker_lib.py

Remove unnecessary double parameter check
Remove check for all candidates for compat (use shortcircuiting)
Fixes #111 

Bugfix: Pickers: Remove api picker slowdown

---

examples/minimal_led_orderable.py
src/faebryk/exporters/documentation/datasheets.py
src/faebryk/library/_F.py
src/faebryk/libs/picker/lcsc.py

Exporter that downloads all PDF datasheets from every (sub)module with the `has_datasheet` trait.

Feature: Exporter: Datasheets
