poetry.lock, pyproject.toml, scripts/profile.sh, tools/profile.sh
Add more choice for profilers.
Integrate better with vscode.
Add profilers as dev deps.
=> Tools: Better profiling script

src/faebryk/core/core.py, src/faebryk/libs/util.py
Some convenience additions for better readability/debugging.
=> Util: Add try_or & core early dup detection

README.md, pyproject.toml, src/faebryk/libs/tools/typer.py, src/faebryk/tools/libadd.py, src/faebryk/tools/main.py, src/faebryk/tools/project.py
Add central faebryk command to run other tools
Add tools/project that helps instantiate the project_template
=> Tools: Add faebryk command; Add tools/project

examples/iterative_design_nand.py, src/faebryk/core/core.py, src/faebryk/core/util.py, src/faebryk/library/Constant.py, src/faebryk/library/ElectricLogic.py, src/faebryk/library/LED.py, src/faebryk/library/Logic.py, src/faebryk/library/Operation.py, src/faebryk/library/PowerSwitchMOSFET.py, src/faebryk/library/Range.py, src/faebryk/library/Resistor.py, src/faebryk/library/Set.py, src/faebryk/library/TI_CD4011BE.py, src/faebryk/libs/e_series.py, src/faebryk/libs/examples/buildutil.py, src/faebryk/libs/examples/pickers.py, src/faebryk/libs/picker/jlcpcb/jlcpcb.py, src/faebryk/libs/picker/lcsc.py, src/faebryk/libs/picker/picker.py, src/faebryk/libs/util.py, test/core/test_parameters.py
Fix iterative nand. WIP need to cleanup commit
=> Fix: Examples: Iterative nand

src/faebryk/core/core.py, src/faebryk/core/util.py, src/faebryk/library/ButtonCell.py, src/faebryk/library/LED.py, src/faebryk/library/Operation.py, src/faebryk/libs/e_series.py, src/faebryk/libs/picker/jlcpcb/jlcpcb.py, src/faebryk/libs/picker/jlcpcb/picker_lib.py, src/faebryk/libs/util.py, test/core/test_parameters.py, test/libs/picker/test_jlcpcb.py, test/libs/test_e_series.py
- Core: Fix inheritance
- Core: Params: Improve get_narrow
- Operation: fix repr
- Picker: JLCPCB e_series param for value
=> Fix: Module inheritance

src/faebryk/exporters/visualize/interactive_graph.py, src/faebryk/exporters/visualize/util.py
Feature: Interactive graph viewer
`interactive_graph` will start a web-server with cytoscape to render an interactive graph
=> Add basic interactive viewer

src/faebryk/libs/kicad/fileformats.py
=> Libs: KiCad: fileformats update footprint

src/faebryk/core/util.py, src/faebryk/exporters/netlist/netlist.py, src/faebryk/exporters/pcb/layout/heuristic_pulls.py, src/faebryk/libs/app/erc.py, src/faebryk/libs/examples/pickers.py, test/core/test_parameters.py, test/library/test_footprints.py
Use import F pattern everywhere
=> Library: Remove direct library imports

src/faebryk/core/node.py
Errors in field construction are too hard to debug given the redirection during construction.
I'm not sure whether I love it yet, but at least you get enough information to easily work out which objects the issue originated in.
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/mattwildoer/Projects/faebryk/src/faebryk/core/node.py:335 in setup_field                  │
│                                                                                                  │
│   332 │   │                                                                                      │
│   333 │   │   def setup_field(name, obj):                                                        │
│   334 │   │   │   try: …
```
=> Core: Improve field construction exceptions

src/faebryk/libs/e_series.py, src/faebryk/libs/picker/jlcpcb/jlcpcb.py, src/faebryk/libs/test/times.py, test/core/test_performance.py, test/libs/picker/test_jlcpcb.py
Make some basic perf tests for picker and optimizie e-series intersect.
=> Picker: Perf test; Cache e-series

src/faebryk/exporters/pcb/kicad/transformer.py
Some utility functions for the PCB Transformer
=> Feature: PCB: Transformer: utils

src/faebryk/exporters/pcb/layout/extrude.py
=> Add: Exporters: PCB: Layout: Reverse order option

src/faebryk/library/LED.py
=> Add: Library: LED: More colors

src/faebryk/library/Mounting_Hole.py, src/faebryk/libs/iso_metric_screw_thread.py
=> Library: Mounting_Hole: Variable diameter and padtype

src/faebryk/exporters/pcb/kicad/transformer.py
Transformer util to place the latest git tag (if available) or git hash on the PCB
=> Exporters: PCB: KiCad: git_version util

src/faebryk/library/CBM9002A_56ILG_Reference_Design.py, src/faebryk/library/QWIIC.py, src/faebryk/library/RS485_Bus_Protection.py, src/faebryk/library/SCD40.py, src/faebryk/library/USB_C_5V_PSU.py, src/faebryk/library/USB_C_PSU_Vertical.py, src/faebryk/library/XL_3528RGBW_WS2812B.py
Replace Const with Range 5%
Improve some esphome traits with is_implemented
=> Library: Remove Constant for physical params

src/faebryk/libs/e_series.py, src/faebryk/libs/picker/jlcpcb/jlcpcb.py, src/faebryk/libs/picker/jlcpcb/picker_lib.py
Add support for inf ranges in e-series
Improve diode picker by using description
Add generic description filter
=> Picker: Inf Ranges; Diode picker++; Descr filter

src/faebryk/exporters/pcb/kicad/transformer.py, src/faebryk/libs/kicad/fileformats.py, src/faebryk/libs/sexp/dataclass_sexp.py, test/common/resources/test.kicad_pcb, test/libs/kicad/test_fileformats.py
Required implementing vargs (positional lists)
=> Libs: kicad fileformat: Implement justifys

src/faebryk/core/graphinterface.py, src/faebryk/core/node.py, src/faebryk/exporters/pcb/kicad/pcb.py, src/faebryk/exporters/pcb/layout/heuristic_decoupling.py, src/faebryk/exporters/pcb/layout/heuristic_pulls.py, src/faebryk/exporters/pcb/layout/typehierarchy.py, src/faebryk/exporters/project/faebryk/project_faebryk.py, src/faebryk/library/CH344.py, src/faebryk/library/Pad.py, src/faebryk/library/Pinmux.py, src/faebryk/libs/picker/picker.py, src/faebryk/libs/util.py, test/libs/kicad/test_fileformats.py
Simple rename of common function, that's actually a function, while that rename is still tractable
=> Rename NotNone function to not_none

examples/minimal_led_orderable.py, src/faebryk/exporters/pcb/kicad/transformer.py, src/faebryk/library/has_pcb_routing_strategy_greedy_direct_line.py, src/faebryk/libs/examples/buildutil.py
All other examples just illustrate a specific concept.
This one makes a (at JLCPCB) orderable design.
=> Examples: Add minimal_led_orderable

src/faebryk/libs/examples/pickers.py
=> Bugfix: Examples: Fix switch picker

src/faebryk/exporters/pcb/kicad/transformer.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Bugfix: Transformer: Alignment

src/faebryk/library/CH344Q_ReferenceDesign.py, src/faebryk/library/Crystal_Oscillator.py, src/faebryk/library/ElecSuper_PSM712_ES.py, src/faebryk/library/Header.py, src/faebryk/library/INA228_ReferenceDesign.py, src/faebryk/library/LDO.py, src/faebryk/library/MultiSPI.py, src/faebryk/library/Powered_Relay.py, src/faebryk/library/RP2040.py, src/faebryk/library/RP2040Pinmux.py, src/faebryk/library/RP2040_ReferenceDesign.py, src/faebryk/library/RS485_Bus_Protection.py, src/faebryk/library/RaspberryPiPicoBase_ReferenceDesign.py, src/faebryk/library/Relay.py, src/faebryk/library/SPIFlash.py, src/faebryk/library/SWDConnector.py, src/faebryk/library/Shenzhen_Kinghelm_Elec_KH_BNC75_3511.py, src/faebryk/library/TD541S485H.py, src/faebryk/library/TECH_PUBLIC_USBLC6_2SC6.py, src/faebryk/library/USB2514B.py, src/faebryk/library/USB2514B_ReferenceDesign.py, src/faebryk/library/USB2_0_ESD_Protection.py, src/faebryk/library/USB2_0_IF.py, src/faebryk/library/Winbond_Elec_W25Q128JVSIQ.py, src/faebryk/library/Winbond_W25Q16JVUXIQ.py, src/faebryk/library/Wuxi_I_core_Elec_AiP74LVC1T45GB236_TR.py, src/faebryk/library/_F.py
Various improvements and fixes
=> Library: Additions, changes and fixes

src/faebryk/libs/picker/jlcpcb/jlcpcb.py
Filters DB on download.
Accelerates pick by at least 2x
=> Picker: JLC: Filter out of stock components from DB

src/faebryk/library/Constant.py, src/faebryk/library/PowerSwitchStatic.py, src/faebryk/library/RP2040.py, src/faebryk/library/USB2_0_ESD_Protection.py, src/faebryk/library/has_multi_picker.py, src/faebryk/libs/examples/pickers.py, src/faebryk/libs/picker/api/api.py, src/faebryk/libs/picker/jlcpcb/jlcpcb.py, src/faebryk/libs/picker/jlcpcb/picker_lib.py, src/faebryk/libs/picker/picker.py
Speedup:
- tolerance filter
- param spec filter
- attribute mention filter
Fixes:
- RP2040 uart ref
- ESD protection no pick needed
- examples: fix rated_voltage params
Fixes examples/mcu.py
=> Libs: Picker: Speedup & Fixes

examples/minimal_led_orderable.py, src/faebryk/library/_F.py, src/faebryk/libs/examples/buildutil.py, src/faebryk/libs/picker/common.py
Add cachepicker that checks all made picks for candidates.
Considerations: This does not optimize for price, it optimizes primarily for speed and secondarily for minimal boms.
=> Libs: Picker: Add CachePicker

pyproject.toml
There was no common ground with atopile/atopile. Now there is!
=> Core: Loosen dependencies to find common ground with atopile

src/faebryk/core/cpp/include/nano.hpp
Add comment pointing to similar issue we are having.
=> Core: Add comment that links nb issue
